- contracts/DxMgnPool.sol
- test/dx_mgn_pool.js
In order to build withdrawels, I need to simulate the participation in some auctions (in particular the incrementation of cummulative pool shares and auction counts).
This diff adds a stub method for that, which will eventually call into the DutchXTrader contract.
Unit test coverage 100%
> Stub to participate in auction

- contracts/DxMgnPool.sol
- test/dx_mgn_pool.js
We have to make sure that at the end of the pooling process the funds are stored in the primary currency (the one, people initially deposited with).
This PR makes sure we only switch into a non-pooling state if the number of auctions is even (after the first auction funds will be in secondary, after the second in primary, etc.)
> Only allow pooling to end after even amount of auction

- contracts/DxMgnPool.sol
- test/dx_mgn_pool.js
isDepositTokenTurn can be calculated from auctionIndex, since auction index increments on every new auction and isDepositTokenTurn flip flops. No need to store redundant state.
> [Easy] Removing redundant smart contract member

- contracts/DxMgnPool.sol
the claiming funciton needs to be called before the unlock function, since the claiming function will issue some more MGN
> Claim before unlock

- contracts/DxMgnPool.sol
- package-lock.json
- package.json
- test/dx_mgn_pool.js
This way, tokens that don't implement the ERC20 standard correctly (such as OMG) can also be used as deposit tokens in this contract.
Unfortunately SafeERC20 throws instead of returning a bool which doesn't allow us to assert on exact error codes.
> Using safeTransferFrom instead of transferFrom

- contracts/DxMgnPool.sol
Adresses #25 
The final claim will always be from secondaryToken back to depositToken (so that we have depositTokens to refund). Thus it's unnecessary to compute buy and sell token in that method.
There is another if statement, which is unnecessary since the call inside can already never fail (it might be slightly more gas efficient in the first auction, but I believe having less branches is more valuable.
> [Easy] remove unnecessary lines

- contracts/DxMgnPool.sol
- migrations/4_deploy_Pool.js
- test/dx_e2e.js
- test/dx_mgn_pool.js
- test/utilities.js
Since difficulty bomb might make it hard to predict the final block number we want to be pooling on and since time measures for dx are already based on timestamps instead of blocktime, this is likely a good idea.
Includes updates to migration scripts and simulation
> Replacing time measurements from block number to block time

- contracts/DxMgnPool.sol
- test/dx_mgn_pool.js
we actually need the 2x totalDeposits,
as otherwise, we would have to change the calculateClaimableMgn or auctionCounting
> Accounts for totalPoolShareCum. only in the depositTokenTurns

- src/migrations/migrations-truffle-5/4_deploy_Pool.js
Fixes issue where `TruffleContract` wrap was not actually getting correct network addresses
- Can be found: `src/migrations/migrations-truffle-5/4_deploy_pool.js`
> fixed issue of TC wrap and get network

- contracts/Coordinator.sol
- contracts/DxMgnPool.sol
- contracts/interfaces/IDutchExchange.sol
- migrations/4_deploy_Pool.js
- scripts/simulation.js
- src/migrations/migrations-truffle-5/4_deploy_Pool.js
- test/dx_coordinator.js
- test/dx_e2e.js
- test/dx_mgn_pool.js
It's much better to use the address that's exposed on the DX directly.
> Remove mgn as ctor argument in DxMgnPool

- contracts/DxMgnPool.sol
We should only withdraw if the amountOfFundsInDx is > 0, not the total deposit. If totalDeposit was > 0 and amountOfFundsInDX, we could get stuck since dx throws whenever we try to withdraw 0 (https://github.com/gnosis/dx-contracts/blob/master/contracts/DutchExchange.sol#L350).
fixes issue #44
> [Easy] Adjust withdraw condition in triggerMGNunlockAndClaimTokens

- contracts/DxMgnPool.sol
buyAndSellToken actually returns the tokens in opposite order (sellAndBuyToken). This was accounted for in the method that called this function, so it was not really a bug but still an inconsistency that should be fixed.
> [Easy] rename buyAndSellToken to correctly reflect return types

- contracts/Coordinator.sol
- test/dx_coordinator.js
- adds an interface for david for easy transaction batching.
- adds necessary tests. Unfortunately, better testing is not possible within the mock contract as safeTransferFrom is only internal transaction and I can not count its invocations.
I am aware that the coordinator contract is not the perfect place to expose this interface. But it was very handy, as this contract is aware of all contracts, from which we are withdrawing.
> adding inteface for transaction batching

- contracts/Coordinator.sol
- scripts/participateInAuction.js
- test/dx_coordinator.js
Alternatively, the currentState could check for update before returning (but this would result in changed to the pool contract rather than the coordinator). This is easier to audit.
> Update pool state before checking current.

- contracts/DxMgnPool.sol
- test/dx_mgn_pool.js
This PR contains the code changes for storing the withdrawn attribute no longer per deposit, but per address.
This was suggested by the auditors, as only all deposits can be withdrawn at once. It is not possible to withdraw parts of the deposits and hence we do not need to store it per deposit
implemented as feedback from auditors suggested....
> storing the withdrawn variable per address, not per deposit

- contracts/DxMgnPool.sol
- test/dx_mgn_pool.js
To test:
```
npx truffle console
migrate --reset
coord = await Coordinator.deployed()
dx1Add = await coord.dxMgnPool1.call()
dxMP1 = await DxMgnPool.at(dx1Add)
const accts = await web3.eth.getAccounts() // can't destructure promises in truffle :cry: 
const [main] = accts
await dxMP1.getAllClaimableMgnAndDeposits.call(main)
// Result { '0': [], '1': [] }
```
Reasoning: can't get those values back as set to private internally (Participation as param) - this works for front-end manipulation
> updateAndGetState + getAllClaimableMgnAndDeposits getters

- contracts/DxMgnPool.sol
Problem: dividing by either `TotalPoolShare` or `TotalPoolSharesCummulative` when 0 = death :dagger: :skull:  As I am relying on websockets to deliver state payloads to me, this change allows my looping function `getAllClaimableMgnandDeposits` to always return something
> Adding default return values to calculateClaimabelMgn and calculateClaimableDeposits

- contracts/DxMgnPool.sol
sets `mapping hasParticpationWithdrawn` to my fav, `public`
I need to check this in the FE for withdrawMGN/Deposit/state updating checks
> hasParticipationWithdrawn = public

- truffle-config.js
We have seen a number of errors with our DxMgnPool bot over the last night. These are likely related to not using a Infura access token for interactions (cf. https://blog.infura.io/infura-dashboard-transition-update-c670945a922a)
This PR makes it so that we use the INFURA_KEY environment variable as a token.
I asked @luarx to change the kubernetes setup with a valid key, so that after we merge this PR our bot should automatically use the correct key.
> Require an Infura key for Rinkeby/Mainnet interaction

- contracts/DxMgnPool.sol
- contracts/interfaces/IDutchExchange.sol
- test/dx_coordinator.js
- test/dx_e2e.js
- test/dx_mgn_pool.js
As Anxo requested, here is the PR for adding the compatibility with OWL token.
It allows setting an approval from the pool to the dx, so that the pool can burn owl.
I implemented the function "setOWLTokenApproval" without any ownership check, as we have no owner and this would be much more work. It has the disadvantage that people could reset our OWL allowance. 
If this is really needed, I can add it later, but first want to get it confirmed, before I put all the work into it.
> compability with OWL token 

- scripts/participateInAuction.js
The previous check for detecting if the MGN is unlocked was not working, the call was not failing and the transaction was
Instead, this PR includes a different check: It verifies the withdraw time of the locked MGN
> Withdraw MGN only when the lock is expired
